
Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-7fq2s[0m
{"level":"warn","ts":1568383670.1223311,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1568383670.122615,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-266jn[0m
{"level":"warn","ts":1568383670.3974843,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1568383670.3997002,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-nikolayantonov-python-flas-wsjzj[0m
{"level":"warn","ts":1568383675.4274144,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1568383675.6095295,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/**************/python-flask-docker.git @ c646571e1fee3758cc9bc7531cb8757b9a697696 in path /workspace/source"}

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:c646571e1fee3758cc9bc7531cb8757b9a697696
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mmeta-pipeline[0m and container [32mstep-merge-pull-refs[0m
SKIP merge-pull-refs: Nothing to merge

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mmeta-pipeline[0m and container [32mstep-create-effective-pipeline[0m
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /builder/home/.**/jenkins-x-versions
performing pack detection in folder /workspace/source
--> Draft detected YAML (44.374380%)
--> Could not find a pack for YAML. Trying to find the next likely language match...
--> Draft detected Perl (15.856596%)
--> Could not find a pack for Perl. Trying to find the next likely language match...
--> Draft detected RPM Spec (15.268528%)
--> Could not find a pack for RPM Spec. Trying to find the next likely language match...
--> Draft detected Text (7.396911%)
--> Could not find a pack for Text. Trying to find the next likely language match...
--> Draft detected Coq (5.179255%)
--> Could not find a pack for Coq. Trying to find the next likely language match...
--> Draft detected Smarty (3.655944%)
--> Could not find a pack for Smarty. Trying to find the next likely language match...
--> Draft detected Python (2.897832%)
selected pack: /builder/home/.**/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/python
Effective pipeline written to jenkins-x-effective.yml

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mmeta-pipeline[0m and container [32mstep-create-tekton-crds[0m
running command: echo \$(**-release-version) > VERSION

running command: ** step tag --version \$(cat VERSION)
Updating chart version in charts/python-flask-docker/Chart.yaml to 0.0.5
Updating repository in charts/python-flask-docker/values.yaml to 955135126607.dkr.ecr.us-west-2.amazonaws.com/**************/python-flask-docker
Updating tag in charts/python-flask-docker/values.yaml to 0.0.5
Tag v0.0.5 created and pushed to remote origin

WARNING: failed to find secret kaniko-secret in namespace **: secrets "kaniko-secret" not found
PipelineActivity for **************-python-flask-docker-master-5
Applying changes 
upserted PipelineResource **************-python-flask-doc for the git repository https://github.com/**************/python-flask-docker.git
upserted Task **************-python-flask-doc-ttqth-from-build-pack-5
upserted Pipeline **************-python-flask-doc-ttqth-5
created PipelineRun **************-python-flask-doc-ttqth-5
created PipelineStructure **************-python-flask-doc-ttqth-5

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-5tcd6[0m
{"level":"warn","ts":1568383685.4353757,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1568383685.4356592,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-gl89k[0m
{"level":"warn","ts":1568383686.4373417,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1568383686.4393542,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source /workspace/source/charts/python-flask-docker\""}

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-nikolayantonov-python-flask-doc-kvj8n[0m
{"level":"warn","ts":1568383692.5021887,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1568383692.6881905,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/**************/python-flask-docker.git @ v0.0.5 in path /workspace/source"}

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:c646571e1fee3758cc9bc7531cb8757b9a697696
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:3.6            
[36mINFO[0m[0001] Error while retrieving image from cache: getting file info: stat /workspace/sha256:3046835b0ec654bc86caf7b4214c3d890bf4e6f636a97036c16ae046ef30bb76: no such file or directory 
[36mINFO[0m[0001] Downloading base image python:3.6            
[36mINFO[0m[0002] Applying label maintainer=lorenz.vanthillo@gmail.com 
[36mINFO[0m[0002] Using files from context: [/workspace/source] 
[36mINFO[0m[0002] Checking for cached layer 955135126607.dkr.ecr.us-west-2.amazonaws.com/todo/cache:336c549a27ef9a46753bfea8db090f2fdbb5edd6886eceebc94a76dbe71387ea... 
[36mINFO[0m[0002] No cached layer found for cmd RUN pip install -r requirements.txt 
[36mINFO[0m[0002] Unpacking rootfs as cmd RUN pip install -r requirements.txt requires it. 
[36mINFO[0m[0021] Taking snapshot of full filesystem...        
[36mINFO[0m[0026] LABEL maintainer="lorenz.vanthillo@gmail.com" 
[36mINFO[0m[0026] Applying label maintainer=lorenz.vanthillo@gmail.com 
[36mINFO[0m[0026] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0026] Using files from context: [/workspace/source] 
[36mINFO[0m[0026] COPY . /app                                  
[36mINFO[0m[0026] Taking snapshot of files...                  
[36mINFO[0m[0026] WORKDIR /app                                 
[36mINFO[0m[0026] cmd: workdir                                 
[36mINFO[0m[0026] Changed working directory to /app            
[36mINFO[0m[0026] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0026] RUN pip install -r requirements.txt          
[36mINFO[0m[0026] cmd: /bin/sh                                 
[36mINFO[0m[0026] args: [-c pip install -r requirements.txt]   
Collecting flask==1.0.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl (91kB)
Collecting Jinja2>=2.10 (from flask==1.0.2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl (124kB)
Collecting itsdangerous>=0.24 (from flask==1.0.2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting click>=5.1 (from flask==1.0.2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting Werkzeug>=0.14 (from flask==1.0.2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b7/61/c0a1adf9ad80db012ed7191af98fa05faa95fa09eceb71bb6fa8b66e6a43/Werkzeug-0.15.6-py2.py3-none-any.whl (328kB)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->flask==1.0.2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: MarkupSafe, Jinja2, itsdangerous, click, Werkzeug, flask
Successfully installed Jinja2-2.10.1 MarkupSafe-1.1.1 Werkzeug-0.15.6 click-7.0 flask-1.0.2 itsdangerous-1.1.0
[36mINFO[0m[0028] Taking snapshot of full filesystem...        
[36mINFO[0m[0031] EXPOSE 8080                                  
[36mINFO[0m[0031] cmd: EXPOSE                                  
[36mINFO[0m[0031] Adding exposed port: 8080/tcp                
[36mINFO[0m[0031] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0031] ENTRYPOINT ["python"]                        
[36mINFO[0m[0031] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0031] CMD ["app/app.py"]                           
[36mINFO[0m[0031] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0031] Pushing layer 955135126607.dkr.ecr.us-west-2.amazonaws.com/todo/cache:336c549a27ef9a46753bfea8db090f2fdbb5edd6886eceebc94a76dbe71387ea to cache now 
[33mWARN[0m[0032] error uploading layer to cache: failed to push to destination 955135126607.dkr.ecr.us-west-2.amazonaws.com/todo/cache:336c549a27ef9a46753bfea8db090f2fdbb5edd6886eceebc94a76dbe71387ea: DENIED: User: arn:aws:sts::955135126607:assumed-role/eksctl-demo-eks-cluster-nodegroup-NodeInstanceRole-1U8BZZ1NSMLJM/i-07787ee6e04390c63 is not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr:us-west-2:955135126607:repository/todo/cache 
2019/09/13 14:08:47 pushed blob: sha256:6d2a0091f25d458555dc59763ab30d94be6e12a8d316cb4f3d09184412b142f3
2019/09/13 14:08:47 pushed blob: sha256:dee499face84ad9b72e21aacba271158972a68d7154cc884abd28c4daf7b2f89
2019/09/13 14:08:48 pushed blob: sha256:ba726ce251d28b466f0f64e487318262c2c0fd4a2d10fcebe70e2b1fb9d9e71b
2019/09/13 14:08:48 pushed blob: sha256:5c64be1d1956477243373372c1ad34cf0ebc799f26767a6ec1371793b789d1b2
2019/09/13 14:08:48 pushed blob: sha256:5c7384adc1f772470764dbd05b7488389810c72a997c6ddfe605940187096a24
2019/09/13 14:08:49 pushed blob: sha256:31ae88fffd1dbfc04a139140969811b50465d21da9cfc37b58ba7ca6f213acab
2019/09/13 14:08:49 pushed blob: sha256:4b5cacb629f5c5323a32103e665756e5d50fe133b3db72d444f370566b713a6a
2019/09/13 14:08:50 pushed blob: sha256:14408c8d4f9a59a5da8f4cc40650be9a8d0991fa1ce1b2fb2767f289a9cc410d
2019/09/13 14:08:53 pushed blob: sha256:1cafc1648588bfdc6289e5007defacc34978f5f3334d97d238bb635d6c30e558
2019/09/13 14:08:55 pushed blob: sha256:4a56a430b2bac33260d6449e162017e2b23076c6411a17b46db67f5b84dde2bd
2019/09/13 14:08:55 pushed blob: sha256:ea67eaa7dd42136287337f879ef20b4ee73baaa108d833d267ef99dd787cdcbf
2019/09/13 14:09:12 pushed blob: sha256:4d134ac3fe4b8dd8136d9e7acbb2708ead2154185b27c09ae62ca099070cfb27
2019/09/13 14:09:12 955135126607.dkr.ecr.us-west-2.amazonaws.com/**************/python-flask-docker:0.0.5: digest: sha256:23495ba5372a5791de4880ab1a9fbecd7afc8c1c0a87d0641dd12a826ac80f7d size: 2067

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/python-flask-docker to an unshallow repository
Generating change log from git ref 8a0503f1835b0b8011e1249d42686709c4186bec => 9b38ab69754a68571969af075a3640842bbcfc68
WARNING: No release found for **************/python-flask-docker and tag v0.0.5 so creating a new release
Updated the release information at https://github.com/**************/python-flask-docker/releases/tag/v0.0.5
generated: /workspace/source/charts/python-flask-docker/templates/release.yaml
Created Release python-flask-docker-0-0-5 resource in namespace **
Updating PipelineActivity **************-python-flask-docker-master-5 with version 0.0.5
Updated PipelineActivities **************-python-flask-docker-master-5 with release notes URL: https://github.com/**************/python-flask-docker/releases/tag/v0.0.5

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file python-flask-docker-0.0.5.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}

Showing logs for build [32mnikolayantonov-python-flask-doc-ttqth-5[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
Promoting app python-flask-docker version 0.0.5 to namespace **-staging
Created Pull Request: https://github.com/**************/environment-crowfair-staging/pull/1
Pull Request https://github.com/**************/environment-crowfair-staging/pull/1 is merged at sha d0b9b60b70e7a52d61e13a5421b263cbf26bf5e5
Pull Request merged but we are not waiting for the update pipeline to complete!
WARNING: Could not find the service URL in namespace **-staging for names python-flask-docker, **-python-flask-docker, **-staging-python-flask-docker
